import Navbar from '@/components/navbar/Navbar'
import Footer from '@/components/Footer'
import { Poppins } from 'next/font/google'
import './globals.css'
import ButtonScrollTop from '@/components/ButtonScrollTop'
import "tw-elements/dist/css/tw-elements.min.css";
import Head from 'next/head'

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '500', '600', '700', '800'] })

export const metadata = {
  title: 'Rinjani Culture',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className} suppressContentEditableWarning={true}>
        <ButtonScrollTop />
        <Navbar />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
